### ISSUE TITLE
It seems as though your code base is not up to date

### ISSUE THREAD

**Issue by tgrowden** [clouie87/nodeAuthTutorial#1]
I was looking through your tutorial here: http://uitblog.com/postgres-with-passport/. I noticed in your comments that you linked to this repo, but it seems as though your code base is not up-to-date when compared with the screenshot snippets in your blog post. There is surprisingly little information available regarding Passport and Postgres, and I was hoping to fork your code if I could get it working. Although, with a bit of modification, I am able to create a user, the code as it stands does not allow for login (it returns an error flash of 'No user found').

**Comment by clouie87** [comment]
Hi Taylor,

Thanks for reaching out! Yes I think I need to go back and rework some of
that tutorial. I believe the Login doesn't work because the data isnt being
passed correctly . Take a look at this passport file. It does the same
thing but better code :)!

https://github.com/clouie87/node-api/blob/master/config/passport.js

Let me know if this helps if not I can look deeper into the issue :)

Cheers,
Carol

**Comment by tgrowden** [comment]
It gives me a bit of a better idea of what I'm doing. Thank you for replying. I hope that, by looking through your code, I'll be able to figure it out.

**Comment by clouie87** [comment]
If not, please let me know :)! I'm more than happy to investigate further
